ip_pattern=0.0.0.0
port_pattern=85
rgb_quant_range=1
dv_color_space=0
dv_metadata=0
eotf=2
max_cll=1000
max_fall=400
max_luma=1000
min_luma=0.005
color_format=0
colorimetry=9
dv_interface=1
dv_map_mode=1
dv_status=1
is_hdr=1
is_ll_dovi=1
is_sdr=0
is_std_dovi=1
max_bpc=10
mode_idx=11
primaries=1
